export  const ADD_PRODUCTS_TO_CART_PENDING = 'ADD_PRODUCTS_TO_CART-pending' ;
export  const ADD_PRODUCTS_TO_CARTS_SUCCESS = 'ADD_PRODUCTS_TO_CART-success' ;
export  const ADD_PRODUCTS_TO_CART_REJECT = 'ADD_PRODUCTS_TO_CART-reject' ;

export  const DELETE_PRODUCTS_TO_CART_REJECT = 'DELETE_PRODUCTS_TO_CART-reject';
export  const DELETE_PRODUCTS_TO_CART_PENDING = 'DELETE_PRODUCTS_TO_CART-reject';
export  const DELETE_PRODUCTS_TO_CART_SUCCESS = 'DELETE_PRODUCTS_TO_CART-success';